name: Update SwaggerHub while developing API
on:
  push:
    branches: [ main ]
env:
  SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}

jobs:
  update-swaggerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: smartbear/swaggerhub-cli@3ee9d3ea4539a3db6c408afc55dbca308f804148
        with:
          args: api:update michaelmelody/DemoAPI -f ./api.yaml

